package model;

public enum MovesEffects {
	
	DANNO,
	
	AUMENTA_ATTACCO,
	AUMENTA_DIFESA,
	AUMENTA_VELOCITA,
	AUMENTA_ATTACCO_SPECIALE,
	AUMENTA_DIFESA_SPECIALE,
	AUMENTA_PRECISIONE,
	AUMENTA_ELUSIONE,
	
	AUMENTA_ATTACCOX2,
	AUMENTA_DIFESAX2,
	AUMENTA_ATTACCO_SPECIALEX2,
	AUMENTA_DIFESA_SPECIALEX2,
	AUMENTA_VELOCITAX2,
	
	AUMENTA_ATTACCO_VELOCITA,
	
	RIDUZIONE_ATTACCO,
	RIDUZIONE_DIFESA,
	RIDUZIONE_VELOCITA,
	RIDUZIONE_ATTACCO_SPECIALE,
	RIDUZIONE_DIFESA_SPECIALE,
	
	RIDUZIONE_ATTACCOX2,
	RIDUZIONE_DIFESAX2,
	RIDUZIONE_VELOCITAX2,
	RIDUZIONE_ATTACCO_SPECIALEX2,
	RIDUZIONE_DIFESA_SPECIALEX2,
	
	DANNO_AUMENTA_VELOCITA,
	DANNO_AUMENTA_ATTACCO,
	
	DANNO_RIDUZIONE_PRECISIONE,
	
	DANNO_RIDUZIONE_DIFESA_E_DIFESA_SPECIALE_SE_STESSO,
	
	RECUPERO_HP,
	DANNO_RECUPERO_HP,
	
	ANNULLA_DANNI
}
